name: swipe_quest
description: Final project of ICM course
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  mobile_scanner: ^1.0.0
  cupertino_icons: ^1.0.2
  scrollable_positioned_list: ^0.2.1
  sensors_plus: ^1.0.4
  audioplayers: ^0.20.1
  qr_flutter: ^4.1.0
  font_awesome_flutter: ^10.4.0
  google_maps_flutter: ^2.0.12


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/

